name: Create porting issues

on:
  issues:
    types: [labeled]

jobs:
  create_issue:
    runs-on: ubuntu-latest
    if: ${{ github.event.label.name == 'Pending/ForwordPort-4.2.0' || github.event.label.name == 'Pending/ForwordPort-4.1.0' }}
    steps:
      - name: Create porting issue
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { owner, repo } = context.repo;
            const { number } = context.issue;
            const issue_title = context.payload.issue.title;
            let label = github.event.label.name;
            let newIssueLabels = ['Type/Patch'];
            let newIssueVersion = label.split('-')[1];
            newIssueLabels.push(label.split('/')[1]);
            
            const issueBody = `
              This Patch Internal was automatically created to track forward porting of *${issue_title}*.
              Original issue: #${number}
              Product Version : $newIssueVersion
            
            `;
            const issueData = {
              title: `[ForwardPort-$newIssueVersion]Porting issue for ${issue_title}`,
              body: issueBody,
              labels: $newIssueLabels,
            };
            await github.rest.issues.create({
              owner,
              repo,
              ...issueData
            });
