name: Create porting issues

on:
  issues:
    types: [labeled]

jobs:
  create_issue:
    runs-on: ubuntu-latest
    if: ${{ github.event.label.name == 'port' }}
    steps:
      - name: Create porting issue
        uses: actions/github-script@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { owner, repo } = context.repo;
            const { number } = context.issue;
            
            const { data } = await github.rest.issues.get({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo
            });            
            
            const { title } = ${data.items[0].title};

            const issueBody = `
              This issue was automatically created to track the porting of ${title}.
              Original issue: #${number}
            `;

            console.log(`Creating porting issue for ${title}`);

            const issueData = {
              title: `Porting issue for ${title}`,
              body: issueBody,
              labels: ['porting'],
            };
            const newIssue = await github.issues.create({
              owner,
              repo,
              ...issueData
            });
            console.log(`Created porting issue ${newIssue.data.number}`);
