name: Add bugs to bugs project

on:
  issues:
    types: [labeled]

jobs:
  add-to-project:
    name: Add issue to project
    runs-on: ubuntu-latest
    steps:
      - name: Add issue to patch project
        uses: actions/add-to-project@main
        with:
          project-url: https://github.com/users/tgtshanika/projects/5/
          github-token: ${{ secrets.ADD_TO_PROJECT_PAT }}
          labeled: Patch, Type/Patch
          label-operator: OR
      - name: Add issue to APIM Internals
        uses: actions/add-to-project@main
        with:
          project-url: https://github.com/users/tgtshanika/projects/4/
          github-token: ${{ secrets.ADD_TO_PROJECT_PAT }}
          labeled: Type/Patch
          label-operator: NOT          
   
