name: Create porting issues

on:
  issues:
    types: [labeled]

jobs:
  create_issue:
    runs-on: ubuntu-latest
    if: ${{ github.event.label.name == 'port' }}
    steps:
      - name: Create porting issue
        uses: actions/github-script@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { owner, repo } = context.repo;
            const { number } = context.issue;
            const { title } = context.issue.title;
            const issueBody = `
              This issue was automatically created to track the porting of ${title}.

              Original issue: #${number}
            `;
            const issueData = {
              title: `Porting issue for ${title}`,
              body: issueBody,
              labels: ['porting'],
            };
            await github.issues.create({
              owner,
              repo,
              ...issueData
            });
