on:
  issues:
    types: [closed]
jobs:
  check-resolution-label:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    if:
      ${{!(
      contains(github.event.issue.labels.*.name, 'Resolution/Merged to Public') ||
      contains(github.event.issue.labels.*.name, 'Resolution/Public Fix N/A')
      )}}
    steps:
      - run: gh issue comment $ISSUE --body "This issue is **NOT** closed with a proper **Resolution/** label. Make sure to add proper reason label before closing. Please add or leave a comment with the proper reason label now.<br /><br />&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;- **Resolution/Cannot Reproduce** - Issue cannot be reproduced.<br />&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;- **Resolution/Duplicate** - Issue is already reported before.<br />&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;- **Resolution/Fixed** - Issue has already been fixed.<br />&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;- **Resolution/Answered** - Issue has already been answered.<br />&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;- **Resolution/Invalid** - Issue is invalid.<br />&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;- **Resolution/Not a bug** - Issue is not a bug.<br />&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;- **Resolution/Postponed** - Issue is postponed.<br />&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;- **Resolution/Won’t Fix** - Issue won't be fixed."
      - run: gh issue reopen $ISSUE
    env:
      GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      ISSUE: ${{ github.event.issue.html_url }}
