on:
  issues:
    types: [closed]
jobs:
  check-resolution-label:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    if:
      ${{ contains(github.event.issue.labels.*.name, 'Type/Patch') && 
      !(
      contains(github.event.issue.labels.*.name, 'Resolution/Duplicate') ||
      contains(github.event.issue.labels.*.name, 'Resolution/Released in Public') ||
      contains(github.event.issue.labels.*.name, 'Resolution/Released N/A in public') ||
      contains(github.event.issue.labels.*.name, 'Resolution/On Hold') ||
      contains(github.event.issue.labels.*.name, 'Resolution/Not a bug') ||
      contains(github.event.issue.labels.*.name, 'Resolution/Won’t Fix')
      )}}
    steps:
      - run: gh issue comment $ISSUE --body "This issue is **NOT** closed with a proper **Resolution/** label. Make sure to add proper reason label before closing. Please add or leave a comment with the proper reason label now.<br /><br />&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;- **Resolution/Released in Public** - The patch is released and the fix is merged to public repo.<br />&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;- **Resolution/Released N/A in public** - The patch is released and the public fix is not applicable.<br />&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;- **Resolution/Duplicate** - Issue is duplicated.<br />&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;- **Resolution/On Hold** - The issue is on hold.<br />&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;- **Resolution/Invalid** - Issue is invalid.<br />&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;- **Resolution/Not a bug** - Issue is not a bug.<br />&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;- **Resolution/Won’t Fix** - Issue won't be fixed."
      - run: gh issue reopen $ISSUE
    env:
      GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      ISSUE: ${{ github.event.issue.html_url }}
